name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  publish:
    name: Publish to Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Dockerhub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push loadout-server AMD64 Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: .
          build-args: |
            API_KEY=${{ secrets.API_KEY }}
          tags: |
            starlightpyro/loadout-server:amd64
            ghcr.io/starlite-project/loadout-server:amd64
      
      - name: Build and push loadout-server armv8 Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: .
          build-args: |
            API_KEY=${{ secrets.API_KEY }}
            RUST_TARGET=aarch64-unknown-linux-musl
            MUSL_TARGET=aarch64-linux-musl
      
